spring:
  application:
    name: redirect-service
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

server:
  port: 5234

aws:
  region: us-west-2
  credential:
    access-key: test
    secret-key: test
  dynamodb:
    endpoint-override: http://localhost:4566
    tables:
      links-table: "Links"
  sns:
    endpoint-override: http://localhost:4566
    topics:
      click-events-topic: "arn:aws:sns:us-west-2:000000000000:click-events"

url-redirection:
  cache:
    ttl: 10m
